# Generated by Django 2.2.5 on 2019-11-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_auto_20191125_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Publicación', 'verbose_name_plural': 'publicaciones'},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Post_img', verbose_name='Imagen'),
        ),
    ]
