# Generated by Django 2.2.5 on 2019-12-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0014_auto_20191128_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
